packages:
  - apps/*
  - packages/*
  - tooling/*
  - workers/*

ignoredBuiltDependencies:
  - core-js
  - core-js-pure
  - protobufjs

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract
  - sharp
  - unrs-resolver
  - lightningcss

overrides:
  "@types/minimatch": 5.1.2
  ioredis: 5.10.0

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
