packages:
  - apps/*
  - packages/*
  - tooling/*

linkWorkspacePackages: true

overrides:
  "@types/minimatch": 5.1.2

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss