import { relations } from "drizzle-orm";
import {
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

import { generateId } from "../utils/id";
import { organization } from "./auth-schema";
import { assets, videos } from "./video-schema";

export const jobTypeEnum = pgEnum("ai_job_type", [
  "transcribe",
  "translate",
  "dub",
  "clean_mode",
  "generate_metadata",
]);

export const jobStatusEnum = pgEnum("ai_job_status", [
  "pending",
  "processing",
  "completed",
  "failed",
]);

export const aiJobs = pgTable("ai_job", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => generateId("job")), // Unique identifier for the AI job
  orgId: text("org_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }), // The organization associated with the job
  videoId: text("video_id").references(() => videos.id, {
    onDelete: "set null",
  }), // The video associated with the job
  params: jsonb("params").default({}).notNull(), // Parameters for the AI job
  type: jobTypeEnum("type").notNull(), // The type of AI job
  provider: text("provider").notNull(), // The provider of the AI service
  tokensUsed: integer("tokens_used").default(0), // The number of tokens used for the job
  costInCents: integer("cost_in_cents").default(0), // The cost of the job in cents
  executionTimeMs: integer("execution_time_ms"), // The time taken to execute the job in milliseconds
  status: jobStatusEnum("status").default("pending").notNull(), // The status of the job
  errorLog: text("error_log"), // Log of any errors that occurred during the job
  outputAssetId: text("output_asset_id").references(() => assets.id, {
    onDelete: "set null",
  }), // The ID of the output asset generated by the job
  createdAt: timestamp("created_at").defaultNow().notNull(), // The timestamp when the job was created
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(), // The timestamp when the job was last updated
});

export const aiJobsRelations = relations(aiJobs, ({ one }) => ({
  organization: one(organization, {
    fields: [aiJobs.orgId],
    references: [organization.id],
  }),
  video: one(videos, {
    fields: [aiJobs.videoId],
    references: [videos.id],
  }),
  outputAsset: one(assets, {
    fields: [aiJobs.outputAssetId],
    references: [assets.id],
  }),
}));
