import { relations } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  vector,
} from "drizzle-orm/pg-core";

import { videos } from "./video-schema";

// Enums
export const transcriptStatusEnum = pgEnum("transcript_status", [
  "pending",
  "processing",
  "completed",
  "failed",
]);

// ============================================
// TRANSCRIPTS
// ============================================

/**
 * Full transcripts for videos - supports multiple languages
 */
export const transcripts = pgTable(
  "transcript",
  {
    id: text("id").primaryKey(),
    videoId: text("video_id")
      .notNull()
      .references(() => videos.id, { onDelete: "cascade" }),

    language: text("language").default("en").notNull(), // ISO 639-1: 'en', 'es', 'fr'
    isOriginal: boolean("is_original").default(true).notNull(),
    isAutoGenerated: boolean("is_auto_generated").default(true).notNull(),

    // Full transcript text (for full-text search)
    content: text("content").notNull(),

    // Timed segments for subtitle display
    // [{ start: 0.0, end: 2.5, text: "Hello world" }, ...]
    segments: jsonb("segments").default([]).notNull(),

    // Word-level timing for karaoke-style subtitles
    // [{ word: "Hello", start: 0.0, end: 0.5, confidence: 0.98 }, ...]
    wordTimings: jsonb("word_timings").default([]),

    // Metadata
    status: transcriptStatusEnum("status").default("pending").notNull(),
    provider: text("provider"), // 'whisper', 'deepgram', 'assembly'
    confidence: integer("confidence"), // Average confidence score 0-100
    durationProcessed: integer("duration_processed"), // Seconds of audio processed
    errorLog: text("error_log"),

    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    index("transcript_videoId_idx").on(table.videoId),
    index("transcript_videoId_language_idx").on(table.videoId, table.language),
  ],
);

/**
 * Transcript segments with embeddings for semantic search
 * Enables "search for concepts" feature
 */
export const transcriptEmbeddings = pgTable(
  "transcript_embedding",
  {
    id: text("id").primaryKey(),
    transcriptId: text("transcript_id")
      .notNull()
      .references(() => transcripts.id, { onDelete: "cascade" }),
    videoId: text("video_id")
      .notNull()
      .references(() => videos.id, { onDelete: "cascade" }),

    // Segment info
    segmentIndex: integer("segment_index").notNull(),
    startTime: integer("start_time").notNull(), // milliseconds
    endTime: integer("end_time").notNull(), // milliseconds
    text: text("text").notNull(),

    // Vector embedding for semantic search (1536 dimensions for OpenAI ada-002)
    embedding: vector("embedding", { dimensions: 1536 }),

    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("embedding_transcriptId_idx").on(table.transcriptId),
    index("embedding_videoId_idx").on(table.videoId),
    // Note: Add HNSW or IVFFlat index for vector search in migrations
  ],
);

// ============================================
// VIDEO CHAPTERS
// ============================================

/**
 * Timestamped chapters for video navigation
 * Can be auto-generated by AI or manually created
 */
export const videoChapters = pgTable(
  "video_chapter",
  {
    id: text("id").primaryKey(),
    videoId: text("video_id")
      .notNull()
      .references(() => videos.id, { onDelete: "cascade" }),

    timestamp: integer("timestamp").notNull(), // Start time in seconds
    endTimestamp: integer("end_timestamp"), // Optional end time
    title: text("title").notNull(),
    description: text("description"), // Optional longer description

    // Thumbnail for chapter preview (like YouTube)
    thumbnailUrl: text("thumbnail_url"),

    // Source tracking
    isAutoGenerated: boolean("is_auto_generated").default(true).notNull(),
    confidence: integer("confidence"), // AI confidence score 0-100

    // Ordering (for manual reordering)
    sortOrder: integer("sort_order").default(0).notNull(),

    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    index("chapter_videoId_idx").on(table.videoId),
    index("chapter_videoId_timestamp_idx").on(table.videoId, table.timestamp),
  ],
);

/**
 * AI-generated video summaries
 */
export const videoSummaries = pgTable(
  "video_summary",
  {
    id: text("id").primaryKey(),
    videoId: text("video_id")
      .notNull()
      .references(() => videos.id, { onDelete: "cascade" }),

    language: text("language").default("en").notNull(),

    // Different summary lengths
    shortSummary: text("short_summary"), // 1-2 sentences
    mediumSummary: text("medium_summary"), // 1 paragraph
    longSummary: text("long_summary"), // Full detailed summary

    // Key points/takeaways
    keyPoints: jsonb("key_points").default([]), // ["Point 1", "Point 2"]

    // Auto-generated tags/topics
    topics: jsonb("topics").default([]), // ["programming", "typescript", "tutorial"]

    // SEO-optimized description
    seoDescription: text("seo_description"),

    // Generation metadata
    provider: text("provider"), // 'openai', 'anthropic'
    modelUsed: text("model_used"), // 'gpt-4', 'claude-3'
    tokensUsed: integer("tokens_used"),

    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    index("summary_videoId_idx").on(table.videoId),
    index("summary_videoId_language_idx").on(table.videoId, table.language),
  ],
);

// ============================================
// RELATIONS
// ============================================

export const transcriptsRelations = relations(transcripts, ({ one, many }) => ({
  video: one(videos, {
    fields: [transcripts.videoId],
    references: [videos.id],
  }),
  embeddings: many(transcriptEmbeddings),
}));

export const transcriptEmbeddingsRelations = relations(
  transcriptEmbeddings,
  ({ one }) => ({
    transcript: one(transcripts, {
      fields: [transcriptEmbeddings.transcriptId],
      references: [transcripts.id],
    }),
    video: one(videos, {
      fields: [transcriptEmbeddings.videoId],
      references: [videos.id],
    }),
  }),
);

export const videoChaptersRelations = relations(videoChapters, ({ one }) => ({
  video: one(videos, {
    fields: [videoChapters.videoId],
    references: [videos.id],
  }),
}));

export const videoSummariesRelations = relations(videoSummaries, ({ one }) => ({
  video: one(videos, {
    fields: [videoSummaries.videoId],
    references: [videos.id],
  }),
}));
