import type { Folder } from "../types/folder";

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 86_400_000).toISOString();

export const MOCK_FOLDERS: Folder[] = [
  {
    id: "fld_marketing",
    name: "Marketing",
    parentId: null,
    visibility: "public",
    color: "blue",
    coverImageUrl: null,
    description: "Public campaign assets. Shareable with partners.",
    pinned: true,
    defaultVideoPrivate: false,
    passwordProtected: false,
    videoCount: 12,
    subfolderCount: 2,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: "fld_product",
    name: "Product",
    parentId: null,
    visibility: "unlisted",
    color: "purple",
    coverImageUrl: null,
    description: "Internal product walkthroughs and demos.",
    pinned: false,
    defaultVideoPrivate: false,
    passwordProtected: false,
    videoCount: 23,
    subfolderCount: 2,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(3),
  },
  {
    id: "fld_board",
    name: "Board meetings",
    parentId: null,
    visibility: "private",
    color: "rose",
    coverImageUrl: null,
    description: "Confidential recordings — password protected.",
    pinned: false,
    defaultVideoPrivate: true,
    passwordProtected: true,
    videoCount: 4,
    subfolderCount: 0,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(7),
  },
  {
    id: "fld_archive",
    name: "Archive",
    parentId: null,
    visibility: "private",
    color: "slate",
    coverImageUrl: null,
    description: null,
    pinned: false,
    defaultVideoPrivate: true,
    passwordProtected: false,
    videoCount: 3,
    subfolderCount: 0,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(30),
  },
  {
    id: "fld_launch",
    name: "Launch",
    parentId: "fld_marketing",
    visibility: "public",
    color: "amber",
    coverImageUrl: null,
    description: "Go-to-market launch videos.",
    pinned: false,
    defaultVideoPrivate: false,
    passwordProtected: false,
    videoCount: 5,
    subfolderCount: 0,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(2),
  },
  {
    id: "fld_social",
    name: "Social",
    parentId: "fld_marketing",
    visibility: "public",
    color: "pink",
    coverImageUrl: null,
    description: "Short-form social clips.",
    pinned: false,
    defaultVideoPrivate: false,
    passwordProtected: false,
    videoCount: 7,
    subfolderCount: 0,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(1),
  },
  {
    id: "fld_tutorials",
    name: "Tutorials",
    parentId: "fld_product",
    visibility: "unlisted",
    color: "green",
    coverImageUrl: null,
    description: "How-to content for customers.",
    pinned: false,
    defaultVideoPrivate: false,
    passwordProtected: false,
    videoCount: 14,
    subfolderCount: 0,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(4),
  },
  {
    id: "fld_demos",
    name: "Demos",
    parentId: "fld_product",
    visibility: "public",
    color: "blue",
    coverImageUrl: null,
    description: null,
    pinned: false,
    defaultVideoPrivate: false,
    passwordProtected: false,
    videoCount: 9,
    subfolderCount: 0,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(5),
  },
];
