import type { VideoItem } from "../types/video-item";

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 86_400_000).toISOString();

export const MOCK_VIDEOS: VideoItem[] = [
  {
    id: "vid_intro",
    folderId: null,
    title: "Welcome to VidcastX",
    durationSec: 93,
    visibility: "public",
    thumbnailHue: 220,
    createdAt: daysAgo(1),
  },
  {
    id: "vid_roadmap",
    folderId: null,
    title: "2026 Product Roadmap",
    durationSec: 846,
    visibility: "unlisted",
    thumbnailHue: 280,
    createdAt: daysAgo(3),
  },
  {
    id: "vid_macos",
    folderId: null,
    title: "macOS 26 hands-on review",
    durationSec: 290,
    visibility: "public",
    thumbnailHue: 200,
    createdAt: daysAgo(1),
  },
  {
    id: "vid_launch_keynote",
    folderId: "fld_launch",
    title: "Launch keynote - final cut",
    durationSec: 1820,
    visibility: "public",
    thumbnailHue: 40,
    createdAt: daysAgo(4),
  },
  {
    id: "vid_launch_trailer",
    folderId: "fld_launch",
    title: "Launch trailer 60s",
    durationSec: 60,
    visibility: "public",
    thumbnailHue: 20,
    createdAt: daysAgo(2),
  },
  {
    id: "vid_social_tiktok1",
    folderId: "fld_social",
    title: "TikTok teaser - feature reveal",
    durationSec: 32,
    visibility: "public",
    thumbnailHue: 330,
    createdAt: daysAgo(1),
  },
  {
    id: "vid_social_insta1",
    folderId: "fld_social",
    title: "Instagram reel - customer story",
    durationSec: 45,
    visibility: "public",
    thumbnailHue: 340,
    createdAt: daysAgo(6),
  },
  {
    id: "vid_tut_gettingstarted",
    folderId: "fld_tutorials",
    title: "Getting started in 5 minutes",
    durationSec: 305,
    visibility: "unlisted",
    thumbnailHue: 145,
    createdAt: daysAgo(10),
  },
  {
    id: "vid_tut_advanced",
    folderId: "fld_tutorials",
    title: "Advanced workflows deep-dive",
    durationSec: 1245,
    visibility: "unlisted",
    thumbnailHue: 155,
    createdAt: daysAgo(14),
  },
  {
    id: "vid_demo_api",
    folderId: "fld_demos",
    title: "Live API demo",
    durationSec: 620,
    visibility: "public",
    thumbnailHue: 210,
    createdAt: daysAgo(8),
  },
  {
    id: "vid_board_q4",
    folderId: "fld_board",
    title: "Q4 board meeting recording",
    durationSec: 3840,
    visibility: "private",
    thumbnailHue: 0,
    createdAt: daysAgo(12),
  },
];
